---
# tasks file for Docker installation and setup

# Update package index
- name: Update apt package index
  apt:
    update_cache: yes

# Install prerequisites for Docker
- name: Install prerequisites for Docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

# Add Docker GPG key
- name: Add Docker GPG key
  command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

# Add Docker repository
- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu focal stable
    state: present

# Install Docker
- name: Install Docker CE and CLI
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

# Ensure Docker service is running and enabled
- name: Ensure Docker service is running and enabled
  service:
    name: docker
    state: started
    enabled: true
